// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: observatory_command.proto

package xrayapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOutboundStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboundStatusRequest) Reset() {
	*x = GetOutboundStatusRequest{}
	mi := &file_observatory_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboundStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboundStatusRequest) ProtoMessage() {}

func (x *GetOutboundStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observatory_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboundStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOutboundStatusRequest) Descriptor() ([]byte, []int) {
	return file_observatory_command_proto_rawDescGZIP(), []int{0}
}

type GetOutboundStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ObservationResult     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboundStatusResponse) Reset() {
	*x = GetOutboundStatusResponse{}
	mi := &file_observatory_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboundStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboundStatusResponse) ProtoMessage() {}

func (x *GetOutboundStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observatory_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboundStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOutboundStatusResponse) Descriptor() ([]byte, []int) {
	return file_observatory_command_proto_rawDescGZIP(), []int{1}
}

func (x *GetOutboundStatusResponse) GetStatus() *ObservationResult {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_observatory_command_proto protoreflect.FileDescriptor

const file_observatory_command_proto_rawDesc = "" +
	"\n" +
	"\x19observatory_command.proto\x12!xray.core.app.observatory.command\x1a\x11observatory.proto\"\x1a\n" +
	"\x18GetOutboundStatusRequest\"a\n" +
	"\x19GetOutboundStatusResponse\x12D\n" +
	"\x06status\x18\x01 \x01(\v2,.xray.core.app.observatory.ObservationResultR\x06status2\xa7\x01\n" +
	"\x12ObservatoryService\x12\x90\x01\n" +
	"\x11GetOutboundStatus\x12;.xray.core.app.observatory.command.GetOutboundStatusRequest\x1a<.xray.core.app.observatory.command.GetOutboundStatusResponse\"\x00B>Z<github.com/popiposter/xkeen-control/internal/xrayapi;xrayapib\x06proto3"

var (
	file_observatory_command_proto_rawDescOnce sync.Once
	file_observatory_command_proto_rawDescData []byte
)

func file_observatory_command_proto_rawDescGZIP() []byte {
	file_observatory_command_proto_rawDescOnce.Do(func() {
		file_observatory_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observatory_command_proto_rawDesc), len(file_observatory_command_proto_rawDesc)))
	})
	return file_observatory_command_proto_rawDescData
}

var file_observatory_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_observatory_command_proto_goTypes = []any{
	(*GetOutboundStatusRequest)(nil),  // 0: xray.core.app.observatory.command.GetOutboundStatusRequest
	(*GetOutboundStatusResponse)(nil), // 1: xray.core.app.observatory.command.GetOutboundStatusResponse
	(*ObservationResult)(nil),         // 2: xray.core.app.observatory.ObservationResult
}
var file_observatory_command_proto_depIdxs = []int32{
	2, // 0: xray.core.app.observatory.command.GetOutboundStatusResponse.status:type_name -> xray.core.app.observatory.ObservationResult
	0, // 1: xray.core.app.observatory.command.ObservatoryService.GetOutboundStatus:input_type -> xray.core.app.observatory.command.GetOutboundStatusRequest
	1, // 2: xray.core.app.observatory.command.ObservatoryService.GetOutboundStatus:output_type -> xray.core.app.observatory.command.GetOutboundStatusResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_observatory_command_proto_init() }
func file_observatory_command_proto_init() {
	if File_observatory_command_proto != nil {
		return
	}
	file_observatory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observatory_command_proto_rawDesc), len(file_observatory_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observatory_command_proto_goTypes,
		DependencyIndexes: file_observatory_command_proto_depIdxs,
		MessageInfos:      file_observatory_command_proto_msgTypes,
	}.Build()
	File_observatory_command_proto = out.File
	file_observatory_command_proto_goTypes = nil
	file_observatory_command_proto_depIdxs = nil
}
