// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: observatory.proto

package xrayapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the response subset of the official Xray Observatory contract.
// Field numbers and fully-qualified names match Xray-core v26.3.27
// (https://github.com/XTLS/Xray-core/tree/v26.3.27).
type ObservationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        []*OutboundStatus      `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObservationResult) Reset() {
	*x = ObservationResult{}
	mi := &file_observatory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservationResult) ProtoMessage() {}

func (x *ObservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_observatory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservationResult.ProtoReflect.Descriptor instead.
func (*ObservationResult) Descriptor() ([]byte, []int) {
	return file_observatory_proto_rawDescGZIP(), []int{0}
}

func (x *ObservationResult) GetStatus() []*OutboundStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type OutboundStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Alive           bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	Delay           int64                  `protobuf:"varint,2,opt,name=delay,proto3" json:"delay,omitempty"`
	LastErrorReason string                 `protobuf:"bytes,3,opt,name=last_error_reason,json=lastErrorReason,proto3" json:"last_error_reason,omitempty"`
	OutboundTag     string                 `protobuf:"bytes,4,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	LastSeenTime    int64                  `protobuf:"varint,5,opt,name=last_seen_time,json=lastSeenTime,proto3" json:"last_seen_time,omitempty"`
	LastTryTime     int64                  `protobuf:"varint,6,opt,name=last_try_time,json=lastTryTime,proto3" json:"last_try_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OutboundStatus) Reset() {
	*x = OutboundStatus{}
	mi := &file_observatory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundStatus) ProtoMessage() {}

func (x *OutboundStatus) ProtoReflect() protoreflect.Message {
	mi := &file_observatory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundStatus.ProtoReflect.Descriptor instead.
func (*OutboundStatus) Descriptor() ([]byte, []int) {
	return file_observatory_proto_rawDescGZIP(), []int{1}
}

func (x *OutboundStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *OutboundStatus) GetDelay() int64 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *OutboundStatus) GetLastErrorReason() string {
	if x != nil {
		return x.LastErrorReason
	}
	return ""
}

func (x *OutboundStatus) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *OutboundStatus) GetLastSeenTime() int64 {
	if x != nil {
		return x.LastSeenTime
	}
	return 0
}

func (x *OutboundStatus) GetLastTryTime() int64 {
	if x != nil {
		return x.LastTryTime
	}
	return 0
}

var File_observatory_proto protoreflect.FileDescriptor

const file_observatory_proto_rawDesc = "" +
	"\n" +
	"\x11observatory.proto\x12\x19xray.core.app.observatory\"V\n" +
	"\x11ObservationResult\x12A\n" +
	"\x06status\x18\x01 \x03(\v2).xray.core.app.observatory.OutboundStatusR\x06status\"\xd5\x01\n" +
	"\x0eOutboundStatus\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12\x14\n" +
	"\x05delay\x18\x02 \x01(\x03R\x05delay\x12*\n" +
	"\x11last_error_reason\x18\x03 \x01(\tR\x0flastErrorReason\x12!\n" +
	"\foutbound_tag\x18\x04 \x01(\tR\voutboundTag\x12$\n" +
	"\x0elast_seen_time\x18\x05 \x01(\x03R\flastSeenTime\x12\"\n" +
	"\rlast_try_time\x18\x06 \x01(\x03R\vlastTryTimeB>Z<github.com/popiposter/xkeen-control/internal/xrayapi;xrayapib\x06proto3"

var (
	file_observatory_proto_rawDescOnce sync.Once
	file_observatory_proto_rawDescData []byte
)

func file_observatory_proto_rawDescGZIP() []byte {
	file_observatory_proto_rawDescOnce.Do(func() {
		file_observatory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observatory_proto_rawDesc), len(file_observatory_proto_rawDesc)))
	})
	return file_observatory_proto_rawDescData
}

var file_observatory_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_observatory_proto_goTypes = []any{
	(*ObservationResult)(nil), // 0: xray.core.app.observatory.ObservationResult
	(*OutboundStatus)(nil),    // 1: xray.core.app.observatory.OutboundStatus
}
var file_observatory_proto_depIdxs = []int32{
	1, // 0: xray.core.app.observatory.ObservationResult.status:type_name -> xray.core.app.observatory.OutboundStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_observatory_proto_init() }
func file_observatory_proto_init() {
	if File_observatory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observatory_proto_rawDesc), len(file_observatory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_observatory_proto_goTypes,
		DependencyIndexes: file_observatory_proto_depIdxs,
		MessageInfos:      file_observatory_proto_msgTypes,
	}.Build()
	File_observatory_proto = out.File
	file_observatory_proto_goTypes = nil
	file_observatory_proto_depIdxs = nil
}
