// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: router_config.proto

package xrayapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config_DomainStrategy int32

const (
	Config_AsIs         Config_DomainStrategy = 0
	Config_IpIfNonMatch Config_DomainStrategy = 2
	Config_IpOnDemand   Config_DomainStrategy = 3
)

// Enum value maps for Config_DomainStrategy.
var (
	Config_DomainStrategy_name = map[int32]string{
		0: "AsIs",
		2: "IpIfNonMatch",
		3: "IpOnDemand",
	}
	Config_DomainStrategy_value = map[string]int32{
		"AsIs":         0,
		"IpIfNonMatch": 2,
		"IpOnDemand":   3,
	}
)

func (x Config_DomainStrategy) Enum() *Config_DomainStrategy {
	p := new(Config_DomainStrategy)
	*p = x
	return p
}

func (x Config_DomainStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_DomainStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_router_config_proto_enumTypes[0].Descriptor()
}

func (Config_DomainStrategy) Type() protoreflect.EnumType {
	return &file_router_config_proto_enumTypes[0]
}

func (x Config_DomainStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_DomainStrategy.Descriptor instead.
func (Config_DomainStrategy) EnumDescriptor() ([]byte, []int) {
	return file_router_config_proto_rawDescGZIP(), []int{1, 0}
}

// Minimal routing configuration subset used to construct the temporary probe
// rule. Field numbers match Xray-core v26.3.27 app/router/config.proto.
type RoutingRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TargetTag:
	//
	//	*RoutingRule_Tag
	//	*RoutingRule_BalancingTag
	TargetTag     isRoutingRule_TargetTag `protobuf_oneof:"target_tag"`
	RuleTag       string                  `protobuf:"bytes,19,opt,name=rule_tag,json=ruleTag,proto3" json:"rule_tag,omitempty"`
	InboundTag    []string                `protobuf:"bytes,8,rep,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	mi := &file_router_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_router_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_router_config_proto_rawDescGZIP(), []int{0}
}

func (x *RoutingRule) GetTargetTag() isRoutingRule_TargetTag {
	if x != nil {
		return x.TargetTag
	}
	return nil
}

func (x *RoutingRule) GetTag() string {
	if x != nil {
		if x, ok := x.TargetTag.(*RoutingRule_Tag); ok {
			return x.Tag
		}
	}
	return ""
}

func (x *RoutingRule) GetBalancingTag() string {
	if x != nil {
		if x, ok := x.TargetTag.(*RoutingRule_BalancingTag); ok {
			return x.BalancingTag
		}
	}
	return ""
}

func (x *RoutingRule) GetRuleTag() string {
	if x != nil {
		return x.RuleTag
	}
	return ""
}

func (x *RoutingRule) GetInboundTag() []string {
	if x != nil {
		return x.InboundTag
	}
	return nil
}

type isRoutingRule_TargetTag interface {
	isRoutingRule_TargetTag()
}

type RoutingRule_Tag struct {
	Tag string `protobuf:"bytes,1,opt,name=tag,proto3,oneof"`
}

type RoutingRule_BalancingTag struct {
	BalancingTag string `protobuf:"bytes,12,opt,name=balancing_tag,json=balancingTag,proto3,oneof"`
}

func (*RoutingRule_Tag) isRoutingRule_TargetTag() {}

func (*RoutingRule_BalancingTag) isRoutingRule_TargetTag() {}

type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DomainStrategy Config_DomainStrategy  `protobuf:"varint,1,opt,name=domain_strategy,json=domainStrategy,proto3,enum=xray.app.router.Config_DomainStrategy" json:"domain_strategy,omitempty"`
	Rule           []*RoutingRule         `protobuf:"bytes,2,rep,name=rule,proto3" json:"rule,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_router_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_router_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_router_config_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetDomainStrategy() Config_DomainStrategy {
	if x != nil {
		return x.DomainStrategy
	}
	return Config_AsIs
}

func (x *Config) GetRule() []*RoutingRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

var File_router_config_proto protoreflect.FileDescriptor

const file_router_config_proto_rawDesc = "" +
	"\n" +
	"\x13router_config.proto\x12\x0fxray.app.router\x1a\x13typed_message.proto\"\x92\x01\n" +
	"\vRoutingRule\x12\x12\n" +
	"\x03tag\x18\x01 \x01(\tH\x00R\x03tag\x12%\n" +
	"\rbalancing_tag\x18\f \x01(\tH\x00R\fbalancingTag\x12\x19\n" +
	"\brule_tag\x18\x13 \x01(\tR\aruleTag\x12\x1f\n" +
	"\vinbound_tag\x18\b \x03(\tR\n" +
	"inboundTagB\f\n" +
	"\n" +
	"target_tag\"\xc9\x01\n" +
	"\x06Config\x12O\n" +
	"\x0fdomain_strategy\x18\x01 \x01(\x0e2&.xray.app.router.Config.DomainStrategyR\x0edomainStrategy\x120\n" +
	"\x04rule\x18\x02 \x03(\v2\x1c.xray.app.router.RoutingRuleR\x04rule\"<\n" +
	"\x0eDomainStrategy\x12\b\n" +
	"\x04AsIs\x10\x00\x12\x10\n" +
	"\fIpIfNonMatch\x10\x02\x12\x0e\n" +
	"\n" +
	"IpOnDemand\x10\x03B?Z=github.com/popiposter/xkeen-keenetic/internal/xrayapi;xrayapib\x06proto3"

var (
	file_router_config_proto_rawDescOnce sync.Once
	file_router_config_proto_rawDescData []byte
)

func file_router_config_proto_rawDescGZIP() []byte {
	file_router_config_proto_rawDescOnce.Do(func() {
		file_router_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_config_proto_rawDesc), len(file_router_config_proto_rawDesc)))
	})
	return file_router_config_proto_rawDescData
}

var file_router_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_router_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_router_config_proto_goTypes = []any{
	(Config_DomainStrategy)(0), // 0: xray.app.router.Config.DomainStrategy
	(*RoutingRule)(nil),        // 1: xray.app.router.RoutingRule
	(*Config)(nil),             // 2: xray.app.router.Config
}
var file_router_config_proto_depIdxs = []int32{
	0, // 0: xray.app.router.Config.domain_strategy:type_name -> xray.app.router.Config.DomainStrategy
	1, // 1: xray.app.router.Config.rule:type_name -> xray.app.router.RoutingRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_router_config_proto_init() }
func file_router_config_proto_init() {
	if File_router_config_proto != nil {
		return
	}
	file_typed_message_proto_init()
	file_router_config_proto_msgTypes[0].OneofWrappers = []any{
		(*RoutingRule_Tag)(nil),
		(*RoutingRule_BalancingTag)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_config_proto_rawDesc), len(file_router_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_config_proto_goTypes,
		DependencyIndexes: file_router_config_proto_depIdxs,
		EnumInfos:         file_router_config_proto_enumTypes,
		MessageInfos:      file_router_config_proto_msgTypes,
	}.Build()
	File_router_config_proto = out.File
	file_router_config_proto_goTypes = nil
	file_router_config_proto_depIdxs = nil
}
