import { IconPlayerPlay, IconPlayerStop, IconRefresh, IconActivity, IconShieldCheck, IconCalendar, IconCalendarOff, IconMap, IconNetwork, IconShieldLock, IconBolt, IconArchive, IconRestore, IconPlug, IconPlus, IconMinus, IconInfoCircle, IconPower, IconGauge, IconArrowsExchange, IconWorld } from '@tabler/icons-react'
export const commandDetails = {
  start: [IconPlayerPlay, 'Start the native traffic service and install its interception rules.'],
  stop: [IconPlayerStop, 'Stop the native traffic service and let XKeen remove its interception rules. Active VPN connections can disconnect.'],
  restart: [IconRefresh, 'Reload all saved Xray configurations by restarting XKeen. Active connections may reconnect.'],
  status: [IconActivity, 'Inspect the current native service state. Does not restart or apply configuration.'],
  'test-xray': [IconShieldCheck, 'Run the native Xray configuration validator and show its output. Does not apply settings.'],
  'update-xkeen': [IconRefresh, 'Update XKeen from its selected channel and answer confirmations in the console. For a stable release, choose Stable with the channel command first. Check release readback afterward; exit zero can also mean cancellation or no update.'],
  'update-xray': [IconRefresh, 'Run the native core updater for the selected version, or let XKeen choose automatically. The service may restart.'],
  'update-geodata': [IconMap, 'Update the installed geodata through XKeen. Native prompts and results appear in the console.'],
  'geodata-sources': [IconMap, 'Choose which geodata sources XKeen installs and updates using its native menu.'],
  'geodata-schedule': [IconCalendar, 'Create or change the native geodata update cron job. Answer XKeen’s day, hour and minute prompts.'],
  'geodata-schedule-remove': [IconCalendarOff, 'Remove only the geodata schedule maintained by XKeen, after its native confirmation.'],
  channel: [IconArrowsExchange, 'Choose the XKeen release channel through its native menu. This is separate from panel updates.'],
  autostart: [IconPower, 'Enable or disable native service autostart. Does not change the panel autostart.'],
  'dns-interception': [IconWorld, 'Enable or disable XKeen DNS interception. This can affect client DNS; inspect the native output and your network configuration.'],
  'router-proxy': [IconNetwork, 'Enable or disable proxying of the router’s Entware traffic through XKeen.'],
  pbr: [IconNetwork, 'Enable or disable native strict policy routing for clients assigned to the XKeen policy.'],
  'pbr-status': [IconInfoCircle, 'Show the native policy-routing state without changing it.'],
  killswitch: [IconShieldLock, 'Enable or disable the native killswitch. When enabled, a VPN failure may block traffic instead of sending it directly.'],
  'killswitch-status': [IconInfoCircle, 'Inspect the native killswitch state without changing it.'],
  'speed-balancer': [IconGauge, 'Open XKeen’s own speed-balancer menu. This is separate from the panel’s bounded speed test and recommendation.'],
  'speed-balancer-on': [IconGauge, 'Enable the native speed balancer. XKeen may run its own throughput measurement and change its configuration.'],
  'speed-balancer-off': [IconGauge, 'Disable XKeen’s own speed balancer through its supported command.'],
  'speed-balancer-status': [IconActivity, 'Inspect the native speed-balancer state and output without starting its measurement.'],
  'backup-xkeen': [IconArchive, 'Ask XKeen to create its own settings backup. Its location and result appear in the native output.'],
  'backup-xray': [IconArchive, 'Ask XKeen to back up the current Xray configuration. Backups can contain VPN credentials.'],
  'restore-xray': [IconRestore, 'Restore Xray configuration using XKeen’s own backup menu and confirmations. The service may restart.'],
  ports: [IconPlug, 'List the ports intercepted by XKeen. Read-only.'],
  'excluded-ports': [IconPlug, 'List the ports excluded from native interception. Read-only.'],
  'ports-add': [IconPlus, 'Add ports or ranges to XKeen’s interception settings. Pass space-separated ports or ranges such as 1000:2000.'],
  'ports-remove': [IconMinus, 'Remove ports or ranges from XKeen’s interception settings.'],
  'excluded-ports-add': [IconPlus, 'Add ports or ranges that should bypass XKeen interception.'],
  'excluded-ports-remove': [IconMinus, 'Remove ports or ranges from the native interception exclusions.'],
  'listen-ports': [IconPlug, 'Show the ports currently listened on by native services. Read-only.'],
  help: [IconInfoCircle, 'Show the help provided by this installed version of XKeen. Does not change settings.'],
}
